# Your project's server will run on localhost:xxxx at this port
PORT: 8000

# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# UnCSS will use these settings
UNCSS_OPTIONS:
  html:
    # Search for used CSS classes in generated HTML files
    - "dist/**/*.html"
  ignore:
    - !!js/regexp .foundation-mq
    - !!js/regexp ^\.is-.*
    - !!js/regexp ^\.js.*
    - !!js/regexp ^\.hqy-.*
    - !!js/regexp ^\.offcanvas.*
    - !!js/regexp ^\.fancybox.*
    - !!js/regexp ^\.ui-.*
    - !!js/regexp ^\.has-.*
    - !!js/regexp ^\.dropdown.*
    - !!js/regexp ^\.multilevel-offcanvas.*
    - !!js/regexp ^\.position-.*
    - !!js/regexp .is-open
    #- !!js/regexp ^\.fa.*

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "src/assets/**/*"
    - "!src/assets/{img,js,scss}/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "node_modules/foundation-sites/scss"
    - "node_modules/motion-ui/src"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/assets/js/app.js"
    - "src/assets/js/homepage.js"
    - "src/assets/js/legacy-app.js"
    - "src/assets/js/app-with-day-night.js"
    - "src/assets/js/global.js"
    - "src/assets/js/welcomeweek.js"
    - "src/assets/js/countdown.js"
    - "src/assets/js/clearing.js"
    - "src/assets/js/phds.js"
    - "src/assets/js/coursefinder.js"
    - "src/assets/js/course-atoz.js"
    - "src/assets/js/coursefinder-upgrade.js"
    - "src/assets/js/coursefinder-upgrade-2.js"
    - "src/assets/js/event.js"
    - "src/assets/js/policy-checker.js"
    - "src/assets/js/sports-fixtures.js"
    - "src/assets/js/fb-geo-test.js"
    - "src/assets/js/course.js"
    - "src/assets/js/qa.js"
