SELECT
P.SPRIDEN_ID,
P.SPRIDEN_PIDM,
P.SPRIDEN_LAST_NAME,
P.SPRIDEN_FIRST_NAME AS first_name,
P.BANNER_PROGRAM_DESC AS course,
P.BANNER_CAMPUS_DESCRIPTION AS campus,
P.UCAS_COURSE_CODE AS ucas,
P.SARADAP_MAJR_CODE_1,
P.SKRSAIN_APPLICANT_NO,
P.AS12_CHECK_RESPONSE_CODE,
P.AS12_PERMISSABLE_YES_NO,
P.AS12_EMAIL_ACCEPTED,
P.AS12_EMAIL_DECLINED,
P.AS12_EMAIL_PROCESSED,
P.LATEST_EMAIL_PROCESSED_DATE,
P.AS12_RESPONSE_EXPLANATION,
P.ORAHASH_APPNO,
P.SKRUCCR_CHOICE_TYPE_NO
FROM
SZVAAPP@UUDEVL.PROD P
WHERE
P.SPRIDEN_PIDM = 786920
AND
P.ORAHASH_APPNO = 4120306217
AND
P.SKRUCCR_CHOICE_TYPE_NO = 4
AND
P.AS12_PERMISSABLE_YES_NO = 'NO'
AND
P.AS12_EMAIL_PROCESSED = 'YES'
AND
(P.AS12_EMAIL_ACCEPTED = 'YES' OR P.AS12_EMAIL_ACCEPTED = 'NO')
AND
(P.AS12_EMAIL_DECLINED = 'YES' OR P.AS12_EMAIL_DECLINED = 'NO')
